### ISSUE TITLE
Manually adding a false access token allows access to protected routes

### ISSUE THREAD

**Issue by bluehatfish** [drehimself/todo-vue#3]
Hi, If you manually add an access_token = 'whatever' to local storage, you can get access to protected routes. 

Would it be better to check the validity of the access token rather than check that one exists in the state?

**Comment by drehimself** [comment]
You are correct. This is the nature of SPAs since the logic for everything lives in the client. The actual data coming back from the server is protected and can only be accessed if the proper token is provided. However, the logic to check if a user is logged in can be tampered with as you stated.
