### ISSUE TITLE
httpOnly cookie instead of local storage?

### ISSUE THREAD

**Issue by MovingGifts** [drehimself/todo-vue#4]
Hi Dre,

In your [youtube video](https://www.youtube.com/watch?v=GRhkhSzyApc&list=PLEhEHUEU3x5q-xB1On4CsLPts0-rZ9oos&index=10) regarding `Authentication`, you stated "I'll look into making a video on how to use cookies instead of local storage.﻿"

Was this video made yet? Thank you so much for all you do!

**Comment by drehimself** [comment]
I haven't had a chance to use cookies instead of local storage. Some people have been asking, will look into it in the future and hopefully post a video.
